# install with conda env create -f environment.yml
name: credit_risk_predictor
channels:
  - conda-forge
  - defaults
dependencies:
  - conda
  - python=3.11.6
  - scipy=1.12.0
  - numpy=1.26.4
  - scikit-learn=1.4.1.post1
  - pandas==2.2.1
  - matplotlib==3.8.3
  - seaborn==0.13.2
  - jupyterlab
  - graphviz==2.50.0
  - pygraphviz==1.9
  - python-graphviz==0.20.1
